### PR TITLE
bitswap/network: refactor connectEventManager more simply in in bsnet 

### LINKED ISSUE #432: Bitswap peer connection race
Experienced via Lassie's CI suite which has suddenly become flaky with some new workloads. Using the [testing/sws-logging](https://github.com/ipfs/boxo/tree/testing/sws-logging) branch here (started by @hannahhoward, continued by me) to diagnose with additional debug printing. It evidences in an inability to communicate with a peer that we know has the block, and bitswap has been told has the block.

See logs below, which come from [here](https://github.com/filecoin-project/lassie/actions/runs/5865827197/job/15903479085?pr=371) using 715365a23d36ccd0fe2c9cf95ec16afa0d50f39b on the [testing/sws-logging](https://github.com/ipfs/boxo/tree/testing/sws-logging) branch. Here's what I believe happens:

* `session#findMorePeers` -> `ProviderQueryManager#FindProvidersAsync`
* `ProviderQueryManager#findProviderWorker` does its thing, processing the queue of providers to connect to, performs a `pqm.network.ConnectTo()` which is goes through (bitswap/network/ipfs_impl.go) `bsnet#ConnectTo()` to just do a basic `host.Connect()`
* We get a `Connected()` notification which is received by (bitswap/network/ipfs_impl.go) `connectEventManager#Connected()` and it does a `c.setState(p, stateResponsive)` on that peer.
* Meanwhile, the `ProviderQueryManager#FindProvidersAsync` has returned, the `Connect()` returned, we even got a `Connected()`, so the `Session` invokes `sessionWantSender#Update(peer, nil, have, nil)`, i.e. the `peer` has the cid `have`, this is a "change".
* In `sessionWantSender` we go from `onChange()` to `processUpdates()` to `updateWantBlockPresence()` to `wantInfo#setPeerBlockPresence()` to `wantInfo#calculateBestPeer()` - we see these in the logs
* After the call to `processUpdates()`, `sessionWantSender` moves on to `sendNextWants()`, which compiles them and calls `sendWants()` which in turn calls `PeerManager#SendWants()`.
* **BUT** it turns out that `PeerManager` doesn't have a `peerQueues` entry for this peer .. yet ..
* Back in `connectEventManager`, the `worker()` (goroutine) loop finally picks up a change, and sees that `p` is now `stateResponsive` so it ends up calling `Bitswap#PeerConnected()` which calls `Client#PeerConnected()` which calls `PeerManager#Connected()` which calls `PeerManager#getOrCreate()` that finally sets up a `peerQueues` entry for that peer; so it's now ready to talk (_"hey, what'd I miss?"_).

I'm a bit fuzzy on what the logs show beyond here and why it doesn't manage to rectify the situation with retries; I guess because it had one chance to take the peer from `FindProvidersAsync` and ask it for the block, and it failed that one chance and there isn't really another.

The async disconnect in `connectEventManager` seems to be the main problem here, perhaps a call to `Connected()` shouldn't return until the state change has been fully propagated.

<details>
<summary>Relevant logs</summary>

```
2023-08-15T09:52:43.126Z	DEBUG	bs:sess	session/session.go:361	FindMorePeers	{"session": 1, "cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq", "pending": 1}
2023-08-15T09:52:43.126Z	DEBUG	bitswap	providerquerymanager/providerquerymanager.go:332	New Provider Query on cid: bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq
2023-08-15T09:52:43.126Z	DEBUG	bitswap	providerquerymanager/providerquerymanager.go:234	Beginning Find Provider Request for cid: bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq
2023-08-15T09:52:43.126Z	DEBUG	lassie/bitswap	bitswaphelpers/indexerrouting.go:86	provider records requested from bitswap, sending back indexer results	{"providerCount": 1}
2023-08-15T09:52:43.126Z	DEBUG	bitswap	providerquerymanager/providerquerymanager.go:244	Connecting to provider 1WRsHVY1dhNKpD...
2023-08-15T09:52:43.126Z	DEBUG	basichost	basic/basic_host.go:737	host QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1 dialing 1WRsHVY1dhNKpD
2023-08-15T09:52:43.126Z	DEBUG	mocknet	mock/mock_peernet.go:119	QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1 (newly) dialing 1WRsHVY1dhNKpD
2023-08-15T09:52:43.126Z	DEBUG	mocknet	mock/mock_peernet.go:132	QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1 dialing 1WRsHVY1dhNKpD openingConn
2023-08-15T09:52:43.126Z	DEBUG	mocknet	mock/mock_peernet.go:140	QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1 opening connection to 1WRsHVY1dhNKpD
2023-08-15T09:52:43.126Z	DEBUG	mocknet	mock/mock_peernet.go:183	1WRsHVY1dhNKpD accepting connection from QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1
2023-08-15T09:52:43.126Z	DEBUG	bitswap_network	network/connecteventmanager.go:159	connectEventManager connected to peer, setting responsive	{"peer": "QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1"}
2023-08-15T09:52:43.126Z	DEBUG	bitswap_network	network/connecteventmanager.go:140	connectEventManager detected peer connectivity	{"peer": "QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1"}
2023-08-15T09:52:43.126Z	DEBUG	mocknet	mock/mock_conn.go:148	Conn.NewStreamWithProtocol: QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1 --> 1WRsHVY1dhNKpD
2023-08-15T09:52:43.126Z	DEBUG	bitswap_network	network/connecteventmanager.go:159	connectEventManager connected to peer, setting responsive	{"peer": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.126Z	DEBUG	mocknet	mock/mock_conn.go:148	Conn.NewStreamWithProtocol: 1WRsHVY1dhNKpD --> QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1
2023-08-15T09:52:43.127Z	DEBUG	basichost	basic/basic_host.go:433	negotiated: /ipfs/id/1.0.0 (took 25.701µs)
2023-08-15T09:52:43.127Z	DEBUG	net/identify	identify/id.go:463	sending snapshot	{"seq": 2, "protocols": ["/fil/datatransfer/1.2.0","/ipfs/bitswap","/ipfs/bitswap/1.0.0","/ipfs/bitswap/1.1.0","/ipfs/bitswap/1.2.0","/ipfs/graphsync/2.0.0","/ipfs/id/1.0.0","/ipfs/id/push/1.0.0"], "addrs": ["/ip6/100::2438:fce9:9d50:c714/tcp/4242"]}
2023-08-15T09:52:43.127Z	DEBUG	net/identify	identify/id.go:468	/ipfs/id/1.0.0 sending message to 1WRsHVY1dhNKpD /ip4/127.0.0.1/tcp/15381
2023-08-15T09:52:43.127Z	DEBUG	net/identify	identify/id.go:519	/ipfs/id/1.0.0 received message from QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1 /ip6/100::2438:fce9:9d50:c714/tcp/4242
2023-08-15T09:52:43.127Z	DEBUG	net/identify	identify/id.go:787	1WRsHVY1dhNKpD received listen addrs for QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1: [/ip6/100::2438:fce9:9d50:c714/tcp/4242]
2023-08-15T09:52:43.127Z	DEBUG	basichost	basic/basic_host.go:433	negotiated: /ipfs/id/1.0.0 (took 398.503µs)
2023-08-15T09:52:43.127Z	DEBUG	net/identify	identify/id.go:463	sending snapshot	{"seq": 2, "protocols": ["/ipfs/bitswap","/ipfs/bitswap/1.0.0","/ipfs/bitswap/1.1.0","/ipfs/bitswap/1.2.0","/ipfs/id/1.0.0","/ipfs/id/push/1.0.0"], "addrs": ["/ip4/127.0.0.1/tcp/15381"]}
2023-08-15T09:52:43.127Z	DEBUG	net/identify	identify/id.go:468	/ipfs/id/1.0.0 sending message to QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1 /ip6/100::2438:fce9:9d50:c714/tcp/4242
2023-08-15T09:52:43.127Z	DEBUG	net/identify	identify/id.go:519	/ipfs/id/1.0.0 received message from 1WRsHVY1dhNKpD /ip4/127.0.0.1/tcp/15381
2023-08-15T09:52:43.127Z	DEBUG	net/identify	identify/id.go:787	QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1 received listen addrs for 1WRsHVY1dhNKpD: [/ip4/127.0.0.1/tcp/15381]
2023-08-15T09:52:43.127Z	WARN	net/identify	identify/id.go:811	QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1 cannot unmarshal key from remote peer: 1WRsHVY1dhNKpD, asn1: structure error: tags don't match (16 vs {class:3 tag:27 length:52 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2
2023-08-15T09:52:43.127Z	DEBUG	basichost	basic/basic_host.go:754	host QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1 finished dialing 1WRsHVY1dhNKpD
2023-08-15T09:52:43.127Z	DEBUG	bitswap	providerquerymanager/providerquerymanager.go:250	Connected to provider 1WRsHVY1dhNKpD
2023-08-15T09:52:43.127Z	DEBUG	bitswap	providerquerymanager/providerquerymanager.go:264	Found 0 providers for cid: bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq
2023-08-15T09:52:43.127Z	DEBUG	net/identify	identify/obsaddr.go:442	added own observed listen addr	{"observed": "/ip6/100::2438:fce9:9d50:c714/tcp/4242"}
2023-08-15T09:52:43.127Z	DEBUG	bitswap	providerquerymanager/providerquerymanager.go:332	Received provider (1WRsHVY1dhNKpD) for cid (bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq)
2023-08-15T09:52:43.127Z	DEBUG	bitswap	providerquerymanager/providerquerymanager.go:332	Finished Provider Query on cid: bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq
2023-08-15T09:52:43.127Z	DEBUG	bs:peermgr	peermanager/peermanager.go:214	pm RegisterSession	{"peer": "1WRsHVY1dhNKpD", "session": 1}
2023-08-15T09:52:43.127Z	DEBUG	bs:sprmgr	sessionpeermanager/sessionpeermanager.go:68	Bitswap: Added peer to session	{"session": 1, "peer": "1WRsHVY1dhNKpD", "peerCount": 1}
2023-08-15T09:52:43.127Z	DEBUG	bs:sess	session/sessionwantsender.go:[65](https://github.com/filecoin-project/lassie/actions/runs/5865827197/job/15903479085?pr=371#step:63:67)7	sws update want block presence	{"cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq", "peerID": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.127Z	DEBUG	bs:sess	session/sessionwantsender.go:764	sws new best peer	{"peerID": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.127Z	DEBUG	bs:sess	session/sessionwantsender.go:657	sws update want block presence	{"cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq", "peerID": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.127Z	DEBUG	bs:sess	session/sessionwantsender.go:764	sws new best peer	{"peerID": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.127Z	DEBUG	bs:sess	session/sessionwantsender.go:535	sws send next wants	{"newly available": ["1WRsHVY1dhNKpD"]}
2023-08-15T09:52:43.127Z	DEBUG	bs:sess	session/sessionwantsender.go:558	sws send new want block	{"cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq", "peerID": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.127Z	DEBUG	bs:sess	session/sessionwantsender.go:580	sws sending wants	{"sends": 1}
2023-08-15T09:52:43.127Z	DEBUG	bs:peermgr	peermanager/peermanager.go:155	pm SendWants	{"peer": "1WRsHVY1dhNKpD", "wantBlocks": 1, "wantHaves": 1}
2023-08-15T09:52:43.127Z	DEBUG	bs:peermgr	peermanager/peermanager.go:159	pm SendWants no peerQueue for	{"peer": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.127Z	DEBUG	bitswap_network	network/connecteventmanager.go:140	connectEventManager detected peer connectivity	{"peer": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.127Z	DEBUG	bs:peermgr	peermanager/peermanager.go:91	pm Connected	{"peer": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.127Z	DEBUG	bs:peermgr	peermanager/peermanager.go:203	pm getOrCreate new peer	{"peer": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.127Z	DEBUG	bitswap	messagequeue/messagequeue.go:280	mq: add want have from broadcast	{"cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq", "peerID": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.127Z	DEBUG	bs:sess	session/sessionwantsender.go:535	sws send next wants	{"newly available": null}
2023-08-15T09:52:43.127Z	DEBUG	bs:sess	session/sessionwantsender.go:546	sws want block in process, no new want block sent	{"cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq"}
2023-08-15T09:52:43.127Z	DEBUG	bs:sess	session/sessionwantsender.go:580	sws sending wants	{"sends": 0}
2023-08-15T09:52:43.129Z	DEBUG	mocknet	mock/mock_conn.go:148	Conn.NewStreamWithProtocol: QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1 --> 1WRsHVY1dhNKpD
2023-08-15T09:52:43.129Z	DEBUG	bitswap	messagequeue/messagequeue.go:[66](https://github.com/filecoin-project/lassie/actions/runs/5865827197/job/15903479085?pr=371#step:63:68)6	sent message	{"type": "WANT_HAVE", "cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq", "local": "QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1", "to": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.129Z	WARN	bitswap_network	network/ipfs_impl.go:245	error setting deadline: set pipe: deadline not supported
2023-08-15T09:52:43.130Z	DEBUG	mocknet	mock/mock_conn.go:148	Conn.NewStreamWithProtocol: QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1 --> 1WRsHVY1dhNKpD
2023-08-15T09:52:43.130Z	WARN	bitswap_network	network/ipfs_impl.go:269	error resetting deadline: set pipe: deadline not supported
2023-08-15T09:52:43.130Z	DEBUG	bs:sess	session/session.go:4[67](https://github.com/filecoin-project/lassie/actions/runs/5865827197/job/15903479085?pr=371#step:63:69)	broadcastWantHaves	{"session": 1, "cids": [{"/":"bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq"}]}
2023-08-15T09:52:43.130Z	DEBUG	basichost	basic/basic_host.go:433	negotiated: /ipfs/bitswap/1.2.0 (took 800.106µs)
2023-08-15T09:52:43.131Z	DEBUG	bitswap_network	network/ipfs_impl.go:427	bitswap net handleNewStream from QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1
2023-08-15T09:52:43.131Z	DEBUG	engine	decision/engine.go:634	Bitswap engine <- msg	{"local": "1WRsHVY1dhNKpD", "from": "QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1", "entryCount": 1}
2023-08-15T09:52:43.131Z	DEBUG	engine	decision/engine.go:638	Bitswap engine <- want-have	{"local": "1WRsHVY1dhNKpD", "from": "QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1", "cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq"}
LinkSystemBlockstore.GetSize bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq
LinkSystemBlockstore.GetSize= bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq 1332
2023-08-15T09:52:43.132Z	DEBUG	engine	decision/engine.go:779	Bitswap engine: block found	{"local": "1WRsHVY1dhNKpD", "from": "QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1", "cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq", "isWantBlock": false}
2023-08-15T09:52:43.132Z	DEBUG	engine	decision/engine.go:545	Bitswap process tasks	{"local": "1WRsHVY1dhNKpD", "taskCount": 1}
2023-08-15T09:52:43.132Z	DEBUG	engine	decision/engine.go:598	Bitswap engine -> msg	{"local": "1WRsHVY1dhNKpD", "to": "QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1", "blockCount": 0, "presenceCount": 1, "size": 38}
2023-08-15T09:52:43.133Z	DEBUG	mocknet	mock/mock_conn.go:148	Conn.NewStreamWithProtocol: 1WRsHVY1dhNKpD --> QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1
2023-08-15T09:52:43.133Z	WARN	bitswap_network	network/ipfs_impl.go:245	error setting deadline: set pipe: deadline not supported
2023-08-15T09:52:43.133Z	DEBUG	basichost	basic/basic_host.go:413	protocol mux failed: stream reset (took 2.485821ms)
2023-08-15T09:52:43.133Z	WARN	bitswap_network	network/ipfs_impl.go:2[69](https://github.com/filecoin-project/lassie/actions/runs/5865827197/job/15903479085?pr=371#step:63:71)	error resetting deadline: set pipe: deadline not supported
2023-08-15T09:52:43.133Z	DEBUG	basichost	basic/basic_host.go:433	negotiated: /ipfs/bitswap/1.2.0 (took 321.[70](https://github.com/filecoin-project/lassie/actions/runs/5865827197/job/15903479085?pr=371#step:63:72)3µs)
2023-08-15T09:52:43.134Z	DEBUG	bitswap_network	network/ipfs_impl.go:427	bitswap net handleNewStream from 1WRsHVY1dhNKpD
2023-08-15T09:52:43.134Z	DEBUG	bs:sess	session/session.go:221	Bitswap <- HAVE	{"local": "QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1", "from": "1WRsHVY1dhNKpD", "cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq", "session": 1}
2023-08-15T09:52:43.134Z	DEBUG	bs:peermgr	peermanager/peermanager.go:214	pm RegisterSession	{"peer": "1WRsHVY1dhNKpD", "session": 1}
2023-08-15T09:52:43.134Z	DEBUG	bs:sess	session/sessionwantsender.go:657	sws update want block presence	{"cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq", "peerID": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.134Z	DEBUG	bs:sess	session/sessionwantsender.go:[76](https://github.com/filecoin-project/lassie/actions/runs/5865827197/job/15903479085?pr=371#step:63:78)4	sws new best peer	{"peerID": "1WRsHVY1dhNKpD"}
2023-08-15T09:52:43.134Z	DEBUG	bs:sess	session/sessionwantsender.go:535	sws send next wants	{"newly available": null}
2023-08-15T09:52:43.134Z	DEBUG	bs:sess	session/sessionwantsender.go:546	sws want block in process, no new want block sent	{"cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq"}
2023-08-15T09:52:43.134Z	DEBUG	bs:sess	session/sessionwantsender.go:580	sws sending wants	{"sends": 0}
2023-08-15T09:52:43.134Z	DEBUG	bitswap-server	server/server.go:325	sent message	{"type": "HAVE", "cid": "bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq", "local": "1WRsHVY1dhNKpD", "to": "QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1"}
2023-08-15T09:52:43.135Z	DEBUG	bitswap-server	server/server.go:3[79](https://github.com/filecoin-project/lassie/actions/runs/5865827197/job/15903479085?pr=371#step:63:81)	sent message	{"peer": "QmRR8VvuQf4Fvr2ptGJj2qjJkmqREJXbF4jv8KkSRLsMj1"}
2023-08-15T09:52:43.135Z	DEBUG	bitswap-server	server/server.go:2[82](https://github.com/filecoin-project/lassie/actions/runs/5865827197/job/15903479085?pr=371#step:63:84)	Bitswap.TaskWorker.Loop	{"ID": 0}
2023-08-15T09:52:43.[139](https://github.com/filecoin-project/lassie/actions/runs/5865827197/job/15903479085?pr=371#step:63:141)Z	DEBUG	bs:sess	session/session.go:467	broadcastWantHaves	{"session": 1, "cids": [{"/":"bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq"}]}
2023-08-15T09:52:43.151Z	DEBUG	bs:sess	session/session.go:467	broadcastWantHaves	{"session": 1, "cids": [{"/":"bafybeifrrglx2issn2had5rtstn3xltla6vxmpjfwfz7o3hapvkynh4zoq"}]}
```
</details>

### PR DESCRIPTION
**Pull request by Jorropo**
I think this is fine because libp2p's .Connect call does not return before the .Connected callback has returned.

This new code also have similar dedup logic and state transitions.

Fixes #432

### CODE REVIEW

**Comment by Jorropo** [comment]
FWIW
```
hugo@rikus ~/k/boxo (fix/432)> RUN_FLAKY_TESTS=1 go test -count=1 ./bitswap/...
ok  	github.com/ipfs/boxo/bitswap	0.699s
ok  	github.com/ipfs/boxo/bitswap/client	0.289s
?   	github.com/ipfs/boxo/bitswap/client/internal	[no test files]
ok  	github.com/ipfs/boxo/bitswap/client/internal/blockpresencemanager	0.025s
?   	github.com/ipfs/boxo/bitswap/client/internal/getter	[no test files]
ok  	github.com/ipfs/boxo/bitswap/client/internal/messagequeue	1.355s
ok  	github.com/ipfs/boxo/bitswap/client/internal/notifications	0.029s
ok  	github.com/ipfs/boxo/bitswap/client/internal/peermanager	0.022s
ok  	github.com/ipfs/boxo/bitswap/client/internal/providerquerymanager	0.187s
ok  	github.com/ipfs/boxo/bitswap/client/internal/session	0.654s
ok  	github.com/ipfs/boxo/bitswap/client/internal/sessioninterestmanager	0.006s
ok  	github.com/ipfs/boxo/bitswap/client/internal/sessionmanager	0.037s
ok  	github.com/ipfs/boxo/bitswap/client/internal/sessionpeermanager	0.007s
?   	github.com/ipfs/boxo/bitswap/client/traceability	[no test files]
ok  	github.com/ipfs/boxo/bitswap/client/wantlist	0.005s
?   	github.com/ipfs/boxo/bitswap/decision	[no test files]
?   	github.com/ipfs/boxo/bitswap/internal	[no test files]
?   	github.com/ipfs/boxo/bitswap/internal/defaults	[no test files]
ok  	github.com/ipfs/boxo/bitswap/internal/testutil	0.003s
ok  	github.com/ipfs/boxo/bitswap/message	0.003s
ok  	github.com/ipfs/boxo/bitswap/message/pb	0.004s
?   	github.com/ipfs/boxo/bitswap/metrics	[no test files]
ok  	github.com/ipfs/boxo/bitswap/network	0.388s
?   	github.com/ipfs/boxo/bitswap/network/internal	[no test files]
?   	github.com/ipfs/boxo/bitswap/server	[no test files]
ok  	github.com/ipfs/boxo/bitswap/server/internal/decision	1.376s
?   	github.com/ipfs/boxo/bitswap/testinstance	[no test files]
ok  	github.com/ipfs/boxo/bitswap/testnet	0.007s
?   	github.com/ipfs/boxo/bitswap/tracer	[no test files]
?   	github.com/ipfs/boxo/bitswap/wantlist	[no test files]
```

**Review by Jorropo — COMMENTED** [review]
This needs tests

**Review by Stebalien — CHANGES_REQUESTED** [review]
This code was written the way it was to decouple connect/disconnect notifications from actually processing those notifications. When overloaded (lots of connect/disconnect events), this code is "well behaved" and will simply end up skipping over short-lived connections.

Specifically:

1. We put the connected/disconnected/unresponsive states into a map when we receive a relevant event.
2. Asynchronously, we update the system state to reflect this.
3. Importantly, we don't spend any time processing "stale" events.

This change will:

1. Block all new connections in libp2p until bitswap can react to them. Blocking in `Connected` and `Disconnected` event handlers is absolutely forbidden.
2. Cause the system to grind to a halt under load as (dis)connect events get delayed behind other (dis)connect events.

So yeah, don't do it.

Also note, this kind of change should be tested on a gateway and bootstrapper before merging. Testing there and then looking at stack dumps, mutex profiles, etc. will usually reveal problems like this.

**Comment by Jorropo** [comment]
> Block all new connections in libp2p until bitswap can react to them. Blocking in Connected and Disconnected event handlers is absolutely forbidden.

We already did that in #435. This is a more efficient and simpler way to do this.
I'm not against not blocking libp2p but this means completely rethinking the connection state flow to let the connect calls from the client go through connectEventManager be required and unblocked from the callback.

---

We could also change the sessions's internals to sort it out with the old behaviour but this isn't the surgical win @rvagg and @hannahhoward were searchig.

**Comment by rvagg** [comment]
OK, well the key thing we need to solve is in the `s.findMorePeers`->`sws.Update` flow: https://github.com/ipfs/boxo/blob/7ec68c5e5adfb13e52f93c20e7c5aadf4860a871/bitswap/client/internal/session/session.go#L393-L397

We need to either make sure that when calling `sws.Update` with a new peer, that it either knows about it already, or is prepared to handle an as-yet unknown peer. That's where the race exists because of the async disconnect.

Some options for exploration that come to mind for me:

* Block in that loop for each peer until we know it's been registered with `PeerConnected`, perhaps `sws.Update` could block, or perhaps we could have a notifier
* Put the peers into a queue that we process async only when they have been properly connected
* Make `sws.Update` OK with receiving a peer that it doesn't already know about, preemptively
* Make only `ProviderFinder.FindProvidersAsync` sync when it comes to performing the `Connect`, i.e. some kind of notifier system within the ProviderFinder so that it only returns a peer once the Connect->PeerConnected flow is known to be complete.

`connectEventManager` can handle multiple listeners, so we should be able to surgically inject a listener just for the purpose of watching this flow.

The problem with all of these of course is in dealing with cleanup of peers we shouldn't have to care about for various reasons.

**Comment by rvagg** [comment]
@Stebalien for reference, this is what we're trying to solve: https://github.com/ipfs/boxo/issues/432#issue-1851234613

**Comment by Stebalien** [comment]
So, what we _should_ be doing there is:

1. Discover the peer.
2. Record that the session is interested in the peer (and record that we think the peer has some CID X). I believe we do the former in the "PeerManager", I don't think we do the latter.
3. Asynchronously try to connect to the peer.

Independently:

1. If/when we get a connection from the peer, find any sessions interested in that peer.
2. Notify the session of the peer.
3. The session will now decide which "wants" it wants to send to the peer, if any. In this case, it _may_ send X, but it may not (because, e.g., it may no longer care about X).

**Pull request closed without merging**
