### PR TITLE
feat: Über Migration (and Boxo rename)

### LINKED ISSUE #215: Rename go-libipfs to boxo
## Done Criteria
1. go-libipfs the repo is renamed to boxo in such a way that existing consumers aren't broken when they dependended on an explicit version of go-libipfs 
2. key consumers of go-libipfs use boxo instead (e.g., Kubo)
3. public docs in this repo that use the term "go-libipfs" have been updated to say "boxo"

## Why Important
A project's name can set expectations on what a project provides to consumers.  We don't want someone to think that they need to use go-libipfs if writing an IPFS implementation in Go.  It may be helpful, but it isn't required.  Worked started in lead up to IPFS Thing 2022 and is ongoing (https://github.com/ipfs/specs/issues/381 ) to drive the message home that IPFS compatibility is very broad.  For example, they must support addressability using CIDs and expose operations (e.g., provision, retrieval) on resources using CIDs.  IPFS implementations don't need to support all the functionality of Kubo or all the functionality that is possible with go-libipfs.  

## Why are we doing this now?
"boxo" has had this history about its name:
* 2021Q4: project pitched and experimented with in "ipfs/go-libipfs": https://github.com/ipfs/kubo/issues/8543
* 202211: started making active effort on it in an incremental fashion. In that process, we renamed "go-libipfs" to "libkubo", but reverted back to go-libipfs because we found it "to be even more confusing since its intention is to have code that is reusable and not Kubo-specific" (see https://github.com/ipfs/kubo/issues/8543#issuecomment-1331161667)
* 202303: @ipfs/kubo-maintainers got feedback from @jbenet on how the "go-libipfs" name can cause confusion about what constitutes an IPFS implementation or set expectations about this repo that we don't want (i.e., that one needs to use this repo for one's IPFS implementation written in go).  

Renames aren't free, but it's better to do it now before even more start depending on it as part of https://github.com/ipfs/boxo/issues/196.

## Why was this name chosen? 
1. ["boxo" is physical toolbox vendor](https://boxousa.com/).  "boxo" the project is intended to be a **toolbox** of modules, tools, and examples that can aid one in their go-based IPFS implementation.
2. Similarity between the "box" and IPFS's "cube" shape.
3. Audible resonance with "kubo", which is the archeologically-rich soil from which "boxo" has sprouted from and "kubo" is at least currently one of the significant consumers of "boxo".
4. "boxo" is short.

## Why wasn't the community given input into the name?
The request for a name change came late while we were part way through https://github.com/ipfs/boxo/issues/196.  That work was already drawing on and impacting other work.  Team resolve to be in limbo was low 1) given current situation and 2) having done a lot of renaming last year with go-ipfs and Kubo, and the name was compelling enough for the reasons listed.

## Tasks
- [x] Validate that github proxying works as expected
- [x] Rename this repo
- [x] Update dependencies
   - [x] kad-dht: https://github.com/libp2p/go-libp2p-kad-dht/pull/832
   - [x] Lotus: https://github.com/filecoin-project/lotus/pull/10562
   - [x] Kubo: https://github.com/ipfs/kubo/pull/9746
   - [x] go-ds-crdt https://github.com/ipfs/go-ds-crdt/pull/200
   - [x] ipfs-lite https://github.com/hsanjuan/ipfs-lite/pull/292
   - [x] ipfs-cluster https://github.com/ipfs-cluster/ipfs-cluster/pull/1901
- [x] Find/replace go-libipfs in this repo

### PR DESCRIPTION
**Pull request by Jorropo**
feat: Über Migration (and Boxo rename)

Include rename from:
  github.com/ipfs/go-libipfs => github.com/ipfs/boxo

This migration was reverted:
  ./blocks => github.com/ipfs/go-block-format

Migrated repos:
- github.com/ipfs/interface-go-ipfs-core         => ./coreiface
- github.com/ipfs/go-pinning-service-http-client => ./pinning/remote/client
- github.com/ipfs/go-path                        => ./path
- github.com/ipfs/go-namesys                     => ./namesys
- github.com/ipfs/go-mfs                         => ./mfs
- github.com/ipfs/go-ipfs-provider               => ./provider
- github.com/ipfs/go-ipfs-pinner                 => ./pinning/pinner
- github.com/ipfs/go-ipfs-keystore               => ./keystore
- github.com/ipfs/go-filestore                   => ./filestore
- github.com/ipfs/go-ipns                        => ./ipns
- github.com/ipfs/go-blockservice                => ./blockservice
- github.com/ipfs/go-ipfs-chunker                => ./chunker
- github.com/ipfs/go-fetcher                     => ./fetcher
- github.com/ipfs/go-ipfs-blockstore             => ./blockstore
- github.com/ipfs/go-ipfs-posinfo                => ./filestore/posinfo
- github.com/ipfs/go-ipfs-util                   => ./util
- github.com/ipfs/go-ipfs-ds-help                => ./datastore/dshelp
- github.com/ipfs/go-verifcid                    => ./verifcid
- github.com/ipfs/go-ipfs-exchange-offline       => ./exchange/offline
- github.com/ipfs/go-ipfs-routing                => ./routing
- github.com/ipfs/go-ipfs-exchange-interface     => ./exchange
- github.com/ipfs/go-unixfs                      => ./ipld/unixfs
- github.com/ipfs/go-merkledag                   => ./ipld/merkledag
- github.com/ipld/go-car                         => ./ipld/car

Fixes #215
Updates #202

### CODE REVIEW

**Comment by guseggert** [comment]
This needs to be tested on Kubo and Lotus before merging right?

**Comment by Jorropo** [comment]
@guseggert this is being tested in Kubo.
I've looked at lotus it should be fine after the fact given we can build `go-ipld-prime` already without even trying (it will require some manual inteligence to put the cut point).

**Comment by BigLep** [comment]
Per verbal maintainer conversation on 2023-03-23, this will be vetted on Lotus as well before merge.

**Comment by guseggert** [comment]
Let me know when this is ready for another review. We need to see what it looks like for Kubo and Lotus to upgrade, so bubbling latest changes up to [the Kubo PR](https://github.com/ipfs/kubo/pull/9746), and opening a PR w/ Lotus (or in a forked repo) seems like a prereq.

**Comment by Jorropo** [comment]
This works in Lotus and Kubo (CI failures are flaky tests and docs gen), builds and non broken tests:
- https://github.com/filecoin-project/lotus/pull/10562
- https://github.com/ipfs/kubo/pull/9746

Imo this is RFM @guseggert

**Comment by guseggert** [comment]
Removed `cmd/car` because it was forcing a newer version of `urfave/cli/v2` which was causing Lotus tests to fail (just some diff tests on CLI output, because that newer version included `--help` in each command output...not a big deal but nice to avoid if we can).  We can add it back later if we want and either downgrade the lib in boxo or make it a separate module so that the lib is not included in the main boxo module.

**Comment by guseggert** [comment]
I spot-checked w/ ipfs-lite (required for ipfs-cluster) and tests fail with a runtime error in go-libp2p-kad-dht due to go-libp2p-kad-dht not being updated yet, the error is from this line: https://github.com/libp2p/go-libp2p-kad-dht/blob/3f53669165720238fdd7a5bb71d60966c0785ef7/internal/config/config.go#L158

So we should probably merge https://github.com/libp2p/go-libp2p-kad-dht/pull/832 first and release it. I think it's already covered by the migration tool because the issue occurs when go-ipns is in your dependency graph which is already covered by the `check-dependencies` command of the migration tool:

```
$ ~/git/boxo/cmd/migrate/migrate check-dependencies
You still have dependencies on repos which have migrated to go-libipfs.
You should consider not having these dependencies to avoid multiple versions of the same code.
You can use 'go mod why' or 'go mod graph' to find the reason for these dependencies.

Dependent module versions:

github.com/ipfs/go-unixfs v0.4.5
github.com/ipfs/go-ipns v0.3.0
github.com/ipfs/go-ipfs-chunker v0.0.5
github.com/ipfs/go-ipfs-blockstore v1.3.0
github.com/ipfs/go-ipfs-util v0.0.2
github.com/ipfs/go-ipfs-ds-help v1.1.0
```

`go mod why` answers this question directly:

```
$ go mod why github.com/ipfs/go-ipns
# github.com/ipfs/go-ipns
github.com/hsanjuan/ipfs-lite
github.com/libp2p/go-libp2p-kad-dht
github.com/libp2p/go-libp2p-kad-dht/internal/config
github.com/ipfs/go-ipns
```

**Comment by guseggert** [comment]
Okay I worked through ipfs-cluster and it builds and CI passes for it too, we're going to need to update github.com/libp2p/go-libp2p-kad-dht and github.com/ipfs/go-ds-crdt in order to unblock ipfs-cluster, so we'll do that after the boxo release.

**Review by guseggert — APPROVED** [review]

**Comment by hsanjuan** [comment]
Thank you @guseggert , I really appreciate that you worried about ipfs-cluster in advance :heart: Send me the PRs, or just let me know when we can upgrade.

**Comment by Kubuxu** [comment]
@Jorropo Kudos to you for preserving the history of migrated repos! Thank you!

**Comment by Jorropo** [comment]
@Kubuxu :heart: you can thx @guseggert too.
My first plan was to do a dumb-ish `git merge --allow-unrelated-histories` and gus made a `git-filter-branch` based python tool which add links and do the tree filtering.

**Pull request merged**
