### PR TITLE
Release v0.10.2

### PR DESCRIPTION
**Pull request by hacdias**
- Gateway sharness will fail as Kubo master has changes that are incompatible.

### CODE REVIEW

**Review by lidel — COMMENTED** [review]
#337 and #395 alone lgtm – as long you have a PR for Kubo 0.21 `release` branch that has sharness green.

**Comment by Jorropo** [comment]
> ```
>  gorelease: go: updates to go.sum needed, disabled by -mod=readonly
> ```

```
$ findf -name "go.mod" | while read p; do cd $(dirname $p); go mod tidy; cd -; done
/home/hugo/Documents/Scripts/boxo
/home/hugo/Documents/Scripts/boxo
git/home/hugo/Documents/Scripts/boxo
 status
/home/hugo/Documents/Scripts/boxo
$ git status
Sur la branche release-v0.10.2
Votre branche est à jour avec 'origin/release-v0.10.2'.

rien à valider, la copie de travail est propre
```

`gorelease` complains about `go.sum` even tho it is good for me, sounds like a bug cc @galargh 
(My random guess is that you `go run .../gorelease` or `go install ../gorealease` inside this repo which adds the `gorelease` entry to the `go.mod` file and make the `go.sum` out of sync.)

**Review by Jorropo — APPROVED** [review]

**Comment by galargh** [comment]
> gorelease complains about go.sum even tho it is good for me, sounds like a bug cc @galargh

I've been able to identify that the issue with `goreleaser` started occurring when we moved from [Go 1.20.4 to Go 1.20.5](https://github.com/golang/go/issues?q=milestone%3AGo1.20.5+label%3ACherryPickApproved). I'm not yet sure why.

**Comment by galargh** [comment]
I managed to reproduce the error in much smaller setup! Looks like it happens when we import go-libp2p 😕 Here's the repo setup where I reproduced it: https://github.com/galargh/gorelease-go1.20.5 And a GHA run that shows it suceeds on 1.20.4 and fails on 1.20.5: https://github.com/galargh/gorelease-go1.20.5/actions/runs/5422828051

**Comment by galargh** [comment]
And it should be fixed in Go 1.20.6 - related issue https://github.com/golang/go/issues/60698

**Pull request merged**
