### PR TITLE
refactor(gateway): use a single path struct internally

### PR DESCRIPTION
**Pull request by aschmahmann**
Builds off of #176 for separate review and merge.

Things that feel good about the PR:
- We are mostly passing a single type around instead of many
- Less reliance on variable naming conventions since we can rely on field names instead

Some things that don't feel great about this PR:
- Which fields in the struct are filled out at any given point in the code is implied rather than type checked
   - Could potentially be fixed by having more types as we progress from `maybeMutable -> immutable -> resolved to last CID + path`
- We use `path.Resolved` which isn't type checked as immutable (if we wanted we could switch to a `finalCID` and `finalPathRemainder` which would probably do the job) 
- There's a bit of a disconnect around _redirects 200s where the finalResolvedPath includes following the redirect but the rest of the contentPathRequest struct is pre-redirect (not sure if this matters much, or if there's an obvious clean way to handle this other than introducing another type or passing more variables around)

Note: aside from this straight refactor there are some issues likely uncovered here (e.g. changing handleNonUnixFSRequestErrors to take a contentPath and choosing a consistent path type to report with).

### CODE REVIEW

**Review by hacdias — COMMENTED** [review]
The changes look fine overall, but I share some of your sentiments. I would first like to ask why we do have 4 paths now. Before we had only 2, then on #176 we have 3. Why 4 now? Is it possible to remove any? 

For example, do we need `immutablePartiallyResolvedPath`, or could we potentially just jump straight to `finalResolvedPath`?

**Comment by aschmahmann** [comment]
> Before we had only 2

We had only two types before `ipath.Path` and `ipath.Resolved`.

> then on https://github.com/ipfs/go-libipfs/pull/176 we have 3

In that PR there are 3 Go types, but 4 different kinds of paths being moved around:
- the requested (maybe mutable) path (`ipath.Path`)
- the immutable version of the requested path (`ImmutablePath`), which was added so we could use some type safety to make sure the data was actually immutable and not have to do type checks or wasted resolutions in `IPFSBackend` implementations
- `maybeResolvedImPath`, not a great name but takes into account that we have done some resolution of the path
- the final resolved path

> Why 4 now? Is it possible to remove any?
> For example, do we need immutablePartiallyResolvedPath, or could we potentially just jump straight to finalResolvedPath?

Nothing new here, but yes I think we could probably remove `immutablePartiallyResolvedPath`. You might have to do a bit of type massaging since `ImmutablePath` is not a `ipath.Resolved` and some functions need to take an `ImmutablePath`.

If you have a way you'd like to change `ImmutablePath` or the function signatures to make things better that's fine. Alternatively, you can probably just `immutablePartiallyResolvedPath` and use type conversions. I'd probably change `finalResolvedPath` to be two fields or a struct with CID + Remainder components though so you don't accidentally "unresolve" part of the path by passing `resolvedPath.String()`.

**Comment by hacdias** [comment]
@lidel @aschmahmann is this something we still want to do, or can this be done in #198?

**Comment by lidel** [comment]
The amount of force pushes we did here makes it impossible to review :see_no_evil: 
@aschmahmann  do you remember which commits are relevant here, we can do interactiver rebase and drop everything else?


I think  we probably want to park this until we have time  for https://github.com/ipfs/boxo/issues/198.

**Comment by aschmahmann** [comment]
closing this until we take a stab at #198

**Pull request closed without merging**
